# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import goods2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(db_index=True, default='0', max_length=20)),
                ('identify', models.CharField(db_index=True, max_length=64)),
                ('source', models.ImageField(max_length=200, upload_to=goods2.models.image_upload_source)),
                ('groundtruth_upc', models.CharField(db_index=True, max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_results', to='goods2.Image')),
            ],
        ),
        migrations.CreateModel(
            name='TrainAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_ip', models.GenericIPAddressField()),
                ('action', models.CharField(choices=[('TA', 'Train All Dataset'), ('TF', 'Train Funiture'), ('TC', 'Train Add Class')], max_length=5)),
                ('model_name', models.CharField(choices=[('ANY', 'not specify'), ('inception_resnet_v2', 'inception resnet V2'), ('nasnet_large', 'nas large'), ('nasnet_mobile', 'nas mobile')], default='ANY', max_length=50)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Waiting'), (5, 'Training'), (10, 'Complete')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='TrainActionUpcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcs', to='goods2.TrainAction')),
            ],
        ),
        migrations.CreateModel(
            name='TrainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(default='', max_length=20)),
                ('traintype', models.PositiveIntegerField(default=0)),
                ('source', models.ImageField(max_length=200, upload_to=goods2.models.train_image_upload_source)),
                ('upc', models.CharField(db_index=True, max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('source_from', models.IntegerField(choices=[(1, 'backend'), (2, 'frontend')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TrainUpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=20, unique=True)),
                ('cnt', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.AddField(
            model_name='trainactionupcs',
            name='train_upc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='goods2.TrainUpc'),
        ),
    ]
