# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGroundTruth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(db_index=True, max_length=64)),
                ('groundtruth_upc', models.CharField(db_index=True, max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='groundtruth_upc',
        ),
        migrations.RemoveField(
            model_name='image',
            name='update_time',
        ),
        migrations.AddField(
            model_name='image',
            name='image_ground_truth',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_images', to='goods2.ImageGroundTruth'),
        ),
    ]
