# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0002_auto_20180613_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(max_length=200)),
                ('checkpoint_prefix', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(choices=[('ANY', 'not specify'), ('inception_resnet_v2', 'inception resnet V2'), ('nasnet_large', 'nas large'), ('nasnet_mobile', 'nas mobile')], default='ANY', max_length=50)),
                ('precision', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (5, 'Training'), (10, 'Complete'), (20, 'Quit')], default=1),
        ),
        migrations.AddField(
            model_name='trainmodel',
            name='train_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_models', to='goods2.TrainAction'),
        ),
        migrations.AddField(
            model_name='trainaction',
            name='f_model_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='child_trains', to='goods2.TrainModel'),
        ),
    ]
