# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0003_auto_20180613_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainaction',
            old_name='f_model_id',
            new_name='f_model',
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='model_name',
            field=models.CharField(choices=[('nasnet_large', 'nas large'), ('nasnet_mobile', 'nas mobile'), ('inception_resnet_v2', 'inception resnet V2')], default='nasnet_large', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='model_name',
            field=models.CharField(choices=[('nasnet_large', 'nas large'), ('nasnet_mobile', 'nas mobile'), ('inception_resnet_v2', 'inception resnet V2')], default='nasnet_large', max_length=50),
        ),
    ]
