# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0004_auto_20180613_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainActionDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_deviceid', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainimage',
            name='traintype',
        ),
        migrations.RemoveField(
            model_name='trainmodel',
            name='model_name',
        ),
        migrations.AddField(
            model_name='trainaction',
            name='max_step',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='trainaction',
            name='train_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (5, 'Training'), (9, 'pause'), (10, 'Complete'), (20, 'Quit')], default=1),
        ),
        migrations.AddField(
            model_name='trainactiondevices',
            name='train_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='goods2.TrainAction'),
        ),
    ]
