# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0005_auto_20180613_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainactionupcs',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainactionupcs',
            name='upc',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
