# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0006_auto_20180613_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainaction',
            name='max_step',
        ),
        migrations.AddField(
            model_name='trainaction',
            name='example_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
