# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0009_auto_20180615_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'transfer_sample'), (2, 'execute_train')], default=1)),
                ('message', models.CharField(default='', max_length=500)),
                ('state', models.IntegerField(choices=[(1, 'Doing'), (10, 'Complete'), (20, 'Error')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
