# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0010_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
