# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0011_auto_20180619_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainaction',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='trainaction',
            name='train_ip',
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (5, 'Training'), (10, 'Complete'), (20, 'Quit')], default=1),
        ),
    ]
