# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0012_auto_20180619_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (5, 'Training'), (9, 'Stop'), (10, 'Complete'), (20, 'Complete with stop')], default=1),
        ),
    ]
