# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0014_evallog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainmodel',
            old_name='checkpoint_prefix',
            new_name='checkpoint_step',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='ip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='model_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
