# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0015_auto_20180620_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainaction',
            name='complete_time',
            field=models.DateTimeField(default=None, verbose_name='train finish time'),
        ),
    ]
