# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0016_trainaction_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainimage',
            name='score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='trainimage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
