# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0017_auto_20180621_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_models', to='goods2.Image')),
                ('train_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods2.TrainModel')),
            ],
        ),
    ]
