# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0019_auto_20180622_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviceid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(default='0', max_length=20, unique=True)),
                ('state', models.IntegerField(choices=[(0, 'testing'), (10, 'commercial')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('commercial_time', models.DateTimeField(default=None, verbose_name='testing finish time')),
            ],
        ),
    ]
