# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0020_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceid',
            name='commercial_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='testing finish time'),
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='complete_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='train finish time'),
        ),
    ]
