# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0021_auto_20180625_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceidPrecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_precisions', to='goods2.Deviceid')),
            ],
        ),
    ]
