# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0024_auto_20180625_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceidExclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(default='0', max_length=20, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
