# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0025_deviceidexclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegroundtruth',
            name='identify',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
