# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0026_auto_20180625_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainaction',
            name='eval_command',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trainaction',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trainaction',
            name='train_command',
            field=models.CharField(default='', max_length=500),
        ),
    ]
