# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0027_auto_20180628_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (5, 'Training'), (9, 'Stop'), (10, 'Complete'), (20, 'Complete with stop'), (30, 'Complete with error')], default=1),
        ),
    ]
