# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0030_auto_20180808_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainactionupcs',
            name='train_upc',
        ),
        migrations.DeleteModel(
            name='TrainUpc',
        ),
    ]
