# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0031_auto_20180809_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceidExclude',
            new_name='DeviceidTrain',
        ),
    ]
