# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods2', '0033_auto_20180810_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upc',
            field=models.CharField(default='', max_length=20),
        ),
    ]
