# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armimage',
            name='tabel_z',
            field=models.IntegerField(default=0),
        ),
    ]
