# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-27 18:57
from __future__ import unicode_literals

import arm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0003_auto_20180921_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmTrainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(default='100000', max_length=20, unique=True)),
                ('rgb_source', models.ImageField(max_length=200, upload_to=arm.models.train_image_upload_source)),
                ('depth_source', models.ImageField(max_length=200, upload_to=arm.models.train_image_upload_source)),
                ('table_z', models.IntegerField(default=0)),
                ('upc', models.CharField(db_index=True, max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
    ]
