# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0004_armtrainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armtrainimage',
            name='deviceid',
            field=models.CharField(default='100000', max_length=20),
        ),
    ]
