# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 15:12
from __future__ import unicode_literals

import arm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0005_auto_20180928_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmCylinderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb_source', models.ImageField(max_length=200, upload_to=arm.models.image_upload_source)),
                ('depth_source', models.ImageField(max_length=200, upload_to=arm.models.image_upload_source)),
                ('table_x', models.IntegerField(default=0)),
                ('table_y', models.IntegerField(default=0)),
                ('table_z', models.IntegerField(default=0)),
                ('result', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
    ]
