SAMPLE_PREFIX = 'sample' # 存储模式识别的样本
STEP20_PREFIX = 'step20'
STEP2S_PREFIX = 'step2S'
STEP2_PREFIX = 'step2'
STEP3_PREFIX = 'step3'
STEP30_PREFIX = 'step30'

MATCH_TYPE_UNKNOWN = -1 # 无效检测
MATCH_TYPE_TRADITION = 0 # 仅使用模式匹配
MATCH_TYPE_DEEPLEARNING = 1 # 仅使用深度学习
MATCH_TYPE_BOTH = 2 # 使用两个检测



CLUSTER_FILE_NAME = 'cluster.txt'