# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('xmin', models.FloatField(default=0.0)),
                ('ymin', models.FloatField(default=0.0)),
                ('xmax', models.FloatField(default=0.0)),
                ('ymax', models.FloatField(default=0.0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_goods', to='goods.Image')),
            ],
        ),
    ]
