# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=800)),
                ('height', models.PositiveIntegerField(default=450)),
                ('source', models.ImageField(height_field='height', max_length=200, upload_to=goods.models.train_image_upload_source, width_field='width')),
                ('upc', models.CharField(max_length=20)),
                ('xmin', models.PositiveIntegerField(default=0)),
                ('ymin', models.PositiveIntegerField(default=0)),
                ('xmax', models.PositiveIntegerField(default=0)),
                ('ymax', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='name',
            new_name='upc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.AlterField(
            model_name='goods',
            name='xmax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='xmin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ymax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ymin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
