# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20171107_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='trainimage',
            name='width',
        ),
    ]
