# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20171107_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BT', 'Begin Train'), ('ST', 'Stop Train'), ('EG', 'Export Graph')], max_length=2)),
                ('desc', models.CharField(max_length=500)),
                ('param', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='trainimage',
            name='source',
            field=models.ImageField(max_length=200, upload_to=goods.models.train_image_upload_source),
        ),
    ]
