# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20171107_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainimage',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
