# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_image_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainimage',
            name='traintype',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
