# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_trainimage_traintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='traintype',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
