# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_actionlog_traintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('BT', 'Begin Train'), ('ST', 'Stop Train'), ('EG', 'Export Graph'), ('TT', 'Test Train')], max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='deviceid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
