# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20171123_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T2', 'Train Step 2'), ('ST', 'Stop Train'), ('E1', 'Export Step 1 Graph'), ('E2', 'Export Step 2 Graph')], max_length=2),
        ),
    ]
