# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(default='0', max_length=20)),
                ('source', models.ImageField(max_length=200, upload_to=goods.models.image_upload_source)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T2', 'Train Step 2'), ('TC', 'Train Only Step 2'), ('ST', 'Stop Train'), ('E1', 'Export Step 1 Graph'), ('E2', 'Export Step 2 Graph')], max_length=2),
        ),
    ]
