# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_trainimageclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('T1', 'Train Step 1'), ('T2', 'Train Step 2'), ('TC', 'Train Only Step 2'), ('ST', 'Stop Train'), ('E1', 'Export Step 1 Graph'), ('E2', 'Export Step 2 Graph')], max_length=2)),
                ('traintype', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('param', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
