# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_auto_20171214_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T2', 'Train Step 2'), ('TC', 'Train Only Step 2'), ('ST', 'Stop All Train')], max_length=2),
        ),
        migrations.AddField(
            model_name='exportaction',
            name='train_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_actions', to='goods.TrainAction'),
        ),
    ]
