# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_auto_20171214_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTrainAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('train_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_train_actions', to='goods.TrainAction')),
            ],
        ),
    ]
