# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_stoptrainaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainaction',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T2', 'Train Step 2'), ('TC', 'Train Only Step 2')], max_length=2),
        ),
    ]
