# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_auto_20171214_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportaction',
            name='backup_postfix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exportaction',
            name='checkpoint_prefix',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
