# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_auto_20171215_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainimage',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
