# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_auto_20171220_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RfidImageCompareAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopCode', models.CharField(default='ARBEEMkAABYQ', max_length=20)),
                ('startTime', models.DateTimeField(verbose_name='start time')),
                ('endTime', models.DateTimeField(verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='RfidTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(db_index=True, verbose_name='transaction date')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_transaction_image', to='goods.Image')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMetrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_upc_num', models.PositiveIntegerField(default=0)),
                ('rfid_minus_upc', models.IntegerField(default=0)),
                ('rfid_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_metrix', to='goods.RfidTransaction')),
            ],
        ),
        migrations.AddField(
            model_name='rfidgoods',
            name='rfid_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_goods', to='goods.RfidTransaction'),
        ),
    ]
