# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_auto_20171221_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidgoods',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
