# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_rfidgoods_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='image',
            name='deviceid',
            field=models.CharField(db_index=True, default='0', max_length=20),
        ),
    ]
