# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0027_auto_20171222_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidimagecompareaction',
            name='deviceid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
