# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_rfidimagecompareaction_deviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidimagecompareaction',
            name='shopCode',
        ),
    ]
