# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0029_remove_rfidimagecompareaction_shopcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidtransaction',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_transaction_image', to='goods.Image'),
        ),
    ]
