# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0030_auto_20171222_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmetrix',
            name='rfid_minus_upc',
        ),
        migrations.AddField(
            model_name='transactionmetrix',
            name='only_image_upc_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmetrix',
            name='only_rfid_upc_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
