# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0031_auto_20171222_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('D2', 'Dataset Step 2')], max_length=2)),
                ('traintype', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('param', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
