# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0032_datasetaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportaction',
            name='backup_postfix',
        ),
        migrations.AddField(
            model_name='datasetaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='exportaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='trainaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
