# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0033_auto_20171228_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.FloatField(default=0.0)),
                ('time2', models.FloatField(default=0.0)),
                ('time3', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_timelog', to='goods.Image')),
            ],
        ),
    ]
