# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_prestep2timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainaction',
            name='is_fineture',
            field=models.BooleanField(default=True),
        ),
    ]
