# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0036_trainaction_is_fineture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainImageOnly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(default='', max_length=20)),
                ('traintype', models.PositiveIntegerField(default=0)),
                ('source', models.ImageField(max_length=200, upload_to=goods.models.train_image_only_upload_source)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
