# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0037_trainimageonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportaction',
            name='model_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
