# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0039_auto_20180201_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportaction',
            name='model_name',
            field=models.CharField(choices=[('ANY', 'not specify'), ('inception_resnet_v2', 'inception resnet V2'), ('nasnet_large', 'nas large')], default='ANY', max_length=50),
        ),
    ]
