# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0040_auto_20180201_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aiinterval',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='lastinterval',
            field=models.FloatField(default=0.0),
        ),
    ]
