# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_auto_20180202_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestep2timelog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='image',
        ),
        migrations.DeleteModel(
            name='PreStep2TimeLog',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
