# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0044_image_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ret',
            field=models.TextField(default=''),
        ),
    ]
