# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_auto_20180314_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(db_index=True, default='0', max_length=20)),
                ('source', models.ImageField(max_length=200, upload_to=goods.models.image_report_upload_source)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
    ]
