# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0046_imagereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportaction',
            name='param',
        ),
        migrations.AddField(
            model_name='exportaction',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
    ]
