# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0047_auto_20180326_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainaction',
            name='serial',
            field=models.CharField(default='', max_length=10),
        ),
    ]
