# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0049_auto_20180330_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainaction',
            name='dataset_dir',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T20', 'Train Step 2_0'), ('T30', 'Train Step 3_n'), ('T2', 'Train Step 2'), ('T3', 'Train Step 3')], max_length=5),
        ),
    ]
