# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0050_auto_20180402_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEvalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_step', models.IntegerField(default=0)),
                ('sample_serial', models.IntegerField(db_index=True, default=0)),
                ('groundtruth_label', models.IntegerField()),
                ('groundtruth_upc', models.CharField(max_length=20)),
                ('detection_label', models.IntegerField()),
                ('detection_upc', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterSampleScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_serial', models.IntegerField(db_index=True, default=0)),
                ('upc_1', models.CharField(max_length=20)),
                ('upc_2', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=20)),
                ('f_id', models.IntegerField(db_index=True, default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterUpcScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_1', models.CharField(max_length=20)),
                ('upc_2', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_dir', models.CharField(default='', max_length=150)),
                ('state', models.IntegerField(choices=[(0, 'not start'), (1, 'doing'), (2, 'complete'), (3, 'stop')], default=0)),
                ('restart_cnt', models.IntegerField(verbose_name=0)),
                ('category_cnt', models.IntegerField(verbose_name=0)),
                ('sample_cnt', models.IntegerField(verbose_name=0)),
                ('step_cnt', models.IntegerField(verbose_name=0)),
                ('model_name', models.CharField(choices=[('ANY', 'not specify'), ('inception_resnet_v2', 'inception resnet V2'), ('nasnet_large', 'nas large'), ('nasnet_mobile', 'nas mobile')], default='ANY', max_length=50)),
                ('m_ap', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.AddField(
            model_name='clusterupcscore',
            name='train_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_task_upcs', to='goods.TrainTask'),
        ),
        migrations.AddField(
            model_name='clustersamplescore',
            name='train_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_task_samples', to='goods.TrainTask'),
        ),
        migrations.AddField(
            model_name='clusterevaldata',
            name='train_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_task_evals', to='goods.TrainTask'),
        ),
    ]
