# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0051_auto_20180408_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterevaldata',
            name='detection_label',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clusterevaldata',
            name='groundtruth_label',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traintask',
            name='category_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traintask',
            name='restart_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traintask',
            name='sample_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traintask',
            name='step_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
