# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0052_auto_20180408_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='traintask',
            name='train_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
