# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0053_traintask_train_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterevaldata',
            name='detection_upc',
        ),
        migrations.RemoveField(
            model_name='clusterevaldata',
            name='groundtruth_upc',
        ),
    ]
