# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0054_auto_20180408_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEvalStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_step', models.IntegerField(default=0)),
                ('train_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_task_evalsteps', to='goods.TrainTask')),
            ],
        ),
    ]
