# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0055_clusterevalstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterstructure',
            name='f_id',
        ),
        migrations.AddField(
            model_name='clusterstructure',
            name='f_upc',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='clusterstructure',
            name='upc',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
