# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0056_auto_20180409_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterstructure',
            name='f_upc',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
    ]
