# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0057_auto_20180409_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterstructure',
            name='update_train_task_id',
            field=models.IntegerField(default=0),
        ),
    ]
