# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0058_clusterstructure_update_train_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traintask',
            old_name='restart_cnt',
            new_name='cluster_cnt',
        ),
    ]
