# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0059_auto_20180418_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(max_length=200, upload_to='')),
                ('upc', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='trainaction',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T20', 'Train Step 2_0'), ('T21', 'Train Step 2_1'), ('T30', 'Train Step 3_n'), ('T2', 'Train Step 2'), ('T3', 'Train Step 3')], max_length=5),
        ),
    ]
