# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0060_auto_20180423_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleimageclass',
            name='deviceid',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
    ]
