# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0061_sampleimageclass_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainaction',
            name='action',
            field=models.CharField(choices=[('T1', 'Train Step 1'), ('T20', 'Train Step 2_0'), ('T21', 'Train Step 2_1'), ('T30', 'Train Step 3_n'), ('T2', 'Train Step 2'), ('T2S', 'Train Step 2 Small Sample'), ('T3', 'Train Step 3'), ('TA', 'Train all in one step')], max_length=5),
        ),
    ]
