# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0065_shelfimage_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfgoods',
            name='shelfid',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='shelfgoods',
            name='shopid',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
