# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0066_auto_20190506_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(db_index=True, default='0', max_length=20)),
                ('ret', models.TextField(default='')),
                ('source', models.ImageField(max_length=200, upload_to=goods.models.image_upload_source)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
    ]
