# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
