# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.IntegerField(unique=True)),
                ('goods_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('upc', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, default='', max_length=50)),
                ('orderid', models.CharField(default='', max_length=20, unique=True)),
                ('order_amount', models.IntegerField()),
                ('pay_amount', models.IntegerField()),
                ('shop_id', models.IntegerField(db_index=True)),
                ('pay_time', models.DateTimeField(verbose_name='pay date')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='goodscf.Goods')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodss', to='goodscf.Payment')),
            ],
        ),
    ]
