# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodscf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, default='', max_length=50)),
                ('r_ui', models.FloatField()),
                ('est', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='goodscf.Goods')),
            ],
        ),
    ]
